### ISSUE TITLE
Use Astro to access existed HBase Table

### ISSUE THREAD

**Issue by WangTaoTheTonic** [HuaweiBigData/astro#13]
We've tested that if we insert data using HBase API and then got an error while reading it using Astro. The reason seems like Astro using different encoding way, but we couldn't find more details.

Hope some guys can help.

**Comment by ravipesala** [comment]
I think this issue same as https://github.com/HuaweiBigData/astro/issues/4.
May be we should open the encoder util and give some examples like 
1) How to write data directly to Hbase and read from Astro.
2) How to read the data from Hbase if data is inserted from Astro.
I think If we can give those 2 examples will solve this issue. I will add another issue to create PR for examples.

**Comment by WangTaoTheTonic** [comment]
@ravipesala Thank you for coments. I will close this per new opened https://github.com/HuaweiBigData/astro/issues/14.
