### ISSUE TITLE
Add examples and update the documentation for reading and writing data directly from Hbase.

### ISSUE THREAD

**Issue by ravipesala** [HuaweiBigData/astro#14]
Recently many users are asked about how to read/write the data in Hbase if the data is handled through Astro.The below two examples with documentation should solve this issue.
1) How to write data directly to Hbase and read from Astro.
2) How to read the data from Hbase if data is inserted from Astro.

Please give your comments

**Comment by chenliang613** [comment]
thanks for your summarizing it

**Comment by ravipesala** [comment]
Added new PR https://github.com/HuaweiBigData/astro/pull/15
