### ISSUE TITLE
The file  "SparkSQLOnHBase_v2.2.docx"  can not  open

### ISSUE THREAD

**Issue by zxcvjl** [HuaweiBigData/astro#17]
I can  not open the file "SparkSQLOnHBase_v2.2.docx".
The office tell me there is error in the content

**Comment by WangTaoTheTonic** [comment]
What is the office version you used? I think it might be about office compatibility.

**Comment by zxcvjl** [comment]
office 2007  I think it's the  problem with office compatibility
