### ISSUE TITLE
one query： Whether Astro support to put record into HBase table which mapped a multiple primaryKey Astro table

### ISSUE THREAD

**Issue by foryou2030** [HuaweiBigData/astro#4]
Step：
(1) Create table in hbase-sql shell:
$SPARK_HBASE_Home/bin/hbase-sql
CREATE TABLE teacher(grade int, class int, subject string, teacher_name string, teacher_age int, PRIMARY KEY (grade, class, subject)) MAPPED BY (hbase_teacher, COLS=[teacher_name=teacher.name, teacher_age=teacher.age]);

(2) put data into hbase table
put 'hbase_teacher', 'row1', 'teacher:age', '40'
put 'hbase_teacher', 'row1', 'teacher:name', 'JIM'

Then, query the Astro table:
do "select count(*) from teacher;", the counts of record have been increased one;
do "select * from teacher;", but it failed,I get the following exception:
Caused by: org.apache.hadoop.hbase.ipc.RemoteWithExtrasException(org.apache.hadoop.hbase.exceptions.OutOfOrderScannerNextException): org.apache.hadoop.hbase.exceptions.OutOfOrderScannerNextException: Expected nextCallSeq: 1 But the nextCallSeq got from client: 0; request=scanner_id: 5 number_of_rows: 1000 close_scanner: false next_call_seq: 0

Whether Astro support to put record into the mapped HBase table when multiple columns map to hbase table rowkey?

**Comment by ravipesala** [comment]
There should not be any problem if the records are inserted through Hbase table directly.But as you created the logical table in Astro with a key PRIMARY KEY (grade, class, subject) , it expects the key of grade+class+subject  with a delimiter of  '0x00'. If you insert the data to Hbase table with expected composed key with delimiter of  '0x00', it should work fine.
I will dig deep and let you know why exactly org.apache.hadoop.hbase.exceptions.OutOfOrderScannerNextException is shown.

**Comment by foryou2030** [comment]
Thanks for you reply. But then I tried to put data intp HBase table like that:
put 'hbase_teacher', '12341234Math', 'teacher:age', '40'
put 'hbase_teacher', '12341234Math', 'teacher:name', 'JIM'

And the result of query astro table is:
+-----------+-----------+-------+------------+-----------+
|      grade|      class|subject|teacher_name|teacher_age|
+-----------+-----------+-------+------------+-----------+
|-1322110156|-1322110156|   Math|         JIM|-1271922688|
+-----------+-----------+-------+------------+-----------+

The rowkey '12341234Math' is converted to '-1322110156' ,' -322110156', 'Math', and the age '40' is '-1271922688'.    How about the code format of numbers?

**Comment by ravipesala** [comment]
I guess you are using hbase shell to put data to Hbase. We can put only strings from hbase shell.Please use Hbase APIs to insert the data. 
Here the problem is 12341234Math is stored as a single String instead of Int(4 bytes)+Int(4bytes)+String. And same problem with age also, it supposed to be int and not string.

**Comment by foryou2030** [comment]
OK, I used hbase shell to put data to Hbase actually. So you mean that it will work fine, if I use Hbase APIs to insert the data that contain Interger type?

**Comment by foryou2030** [comment]
I tried to use Hbase APIs to insert , but the same result:
+-----------+-----------+-------+------------+-----------+
|      grade|      class|subject|teacher_name|teacher_age|
+-----------+-----------+-------+------------+-----------+
|-1322110156|-1322110156|English|         Tom|-1271922688|
|          1|          1|   Math|         Tom|         45|
+-----------+-----------+-------+------------+-----------+

The following is my app code :

   val HTable = SingletonHTableJava.getHTable("2181", "linux-120.site, linux-121.site, linux-    122.site", "hbase_teacher")
    val rowKey = "12341234English"
    val columnFam = "teacher"
    val name = "Tom"
    val age = "40"
    val put = new Put(Bytes.toBytes(rowKey))
    put.add(Bytes.toBytes(columnFam),Bytes.toBytes("name"), Bytes.toBytes(name))
    put.add(Bytes.toBytes(columnFam),Bytes.toBytes("age"), Bytes.toBytes(age))
    HTable.put(put)

**Comment by ravipesala** [comment]
You are still using rowKey and age as String only. Please use like Int(4 bytes)+Int(4bytes)+String. Please refer the below code.
int grade = 1234
int class = 1234
String subject = "English"
String name = "Tom"
int age = 40
byte[] rowkey = new byte[4+4+subject.length()]
System.arrayCopy(Bytes.toBytes(grade),0,rowkey,0,4)
System.arrayCopy(Bytes.toBytes(class ),0,rowkey,4,4)
System.arrayCopy(Bytes.toBytes(subject),0,rowkey,8,subject.length())
Put put = new Put(rowkey);
put.add(Bytes.toBytes(columnFam),Bytes.toBytes("name"), Bytes.toBytes(name))
put.add(Bytes.toBytes(columnFam),Bytes.toBytes("age"), Bytes.toBytes(age))

**Comment by foryou2030** [comment]
Thanks. I   tried again refer your code, the following is the result :

query Hbase
hbase(main):031:0> scan 'hbase_teacher'
ROW                                                          COLUMN+CELL                                                                                                                                                                    
 \x00\x00\x04\xD2\x00\x00\x04\xD2English                     column=teacher:age, timestamp=1444873385425, value=\x00\x00\x00(                                                                                                               
 \x00\x00\x04\xD2\x00\x00\x04\xD2English                     column=teacher:name, timestamp=1444873385425, value=Tom

query Astro
+-----------+-----------+-------+------------+-----------+
|      grade|      class|subject|teacher_name|teacher_age|
+-----------+-----------+-------+------------+-----------+
|-2147482414|-2147482414|English|          Tom|-2147483608|
+-----------+-----------+-------+------------+-----------+

**Comment by ravipesala** [comment]
Here the problem is conversion of datatype to bytes is different in the above program and Astro. We used ```Bytes.toBytes(int)``` to convert to bytes. But Astro uses ```BytesUtils``` to convert the same. If you use the same ```BytesUtils``` ,it solves the problem. Please check the below code, I have tested it and works fine.

```
        Configuration config = HBaseConfiguration.create();
        HTable table = new HTable(config, "hbase_teacher");
        int grade = 1234;
        int class1 = 1234;
        String subject = "English1";
        String name = "Tom";
        int age = 40;
        ToBytesUtils bu = BinaryBytesUtils.create(DataType.fromCaseClassString("IntegerType"));
        byte[] rowkey = new byte[4+4+subject.length()];
        System.arraycopy(bu.toBytes(grade), 0, rowkey, 0, 4);
        System.arraycopy(bu.toBytes(class1), 0, rowkey, 4, 4);
        System.arraycopy(Bytes.toBytes(subject), 0, rowkey, 8, subject.length());
        Put put = new Put(rowkey);
        put.add(Bytes.toBytes("teacher"),Bytes.toBytes("name"), Bytes.toBytes(name));
        put.add(Bytes.toBytes("teacher"),Bytes.toBytes("age"), bu.toBytes(age));
        table.put(put);
        table.close();
```

**Comment by Zhangshunyu** [comment]
I have repeated the above operation using BinaryBytesUtils as you said, and the query result of ASTRO is correct：
+-----+-----+--------+------------+-----------+
|grade|class| subject|teacher_name|teacher_age|
+-----+-----+--------+------------+-----------+
| 1234| 1234|English1| Tom| 40|
+-----+-----+--------+------------+----------

 but I am puzzled that the query result of HBASE is as following：
\x80\x00\x04\xD2\x80\x00\x04\xD2English1 column=teacher:age, timestamp=1445223720507, value=\x80\x00\x00( 
\x80\x00\x04\xD2\x80\x00\x04\xD2English1 column=teacher:name, timestamp=1445223720507, value=Tom

We can find that “1234| 1234|English1” is stored as “\x80\x00\x04\xD2\x80\x00\x04\xD2English1”
in HBASE.

**Comment by ravipesala** [comment]
Yes, it stored as bytes in Hbase so if you do scan in Hbase it prints as above as it does not use our BinaryBytesUtils to convert bytes to respective datatype.There is no problem in that.
If you want to get the data from Hbase directly then you should java API to scan and convert the bytes to respective datatype using BinaryBytesUtils.

**Comment by ravipesala** [comment]
Added an issue for new PR https://github.com/HuaweiBigData/astro/issues/14
